---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whisper
  labels:
    app: whisper
spec:
  selector:
    matchLabels:
      app: whisper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: whisper
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
      containers:
        - name: whisper
          image: ghcr.io/alexgustafsson/wyoming-kb-whisper
          args:
            - --model
            - base
          env:
            - name: TZ
              value: Europe/Stockholm
            - name: HF_HUB_CACHE
              value: /tmp
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
          ports:
            - name: wyoming
              containerPort: 10300
              protocol: TCP
      volumes:
        # Make sure to change this mount
        - name: data
          hostPath:
            path: /home/alex/whisper/data
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: whisper
spec:
  ports:
    - protocol: TCP
      name: wymoing
      port: 10300
  selector:
    app: whisper
